Repository etclabscore/go-ethereum, pull requests merged in 2019-09, with the labels that each got.

#20 Agharta/eip1014 create2
  cmd/evm/main.go
  core/config.go
  core/execution.go
  core/vm/environment.go
  core/vm/gas.go
  core/vm/instructions.go
  core/vm/instructions_test.go
  core/vm/jump_table.go
  core/vm/jump_table_test.go
  core/vm/opcodes.go
  core/vm/runtime/env.go
  core/vm/runtime/runtime.go
  core/vm/vm.go
  core/vm_env.go
  crypto/crypto.go
  go.sum
  params/protocol_params.go
  tests/init.go
  tests/state_test.go
  tests/util.go
Labels: PR: 6 Backport, Priority: 2 High, Type: Core

#48 Windows build fix and makefile update
  .circleci/config.yml
  Makefile
  core/assets/assets.go
  core/defaults_test.go
  go.mod
  go.sum
  rpc/ipc_windows.go
Labels: PR: 1 Needs Review, Type: Build

#11 added whiteblock config/script
  .circleci/config.yml
  scripts/whiteblock.sh
Labels: PR: 0 In Progress, PR: 4 Patch, Priority: 2 High, Type: Build, Type: Tests
